-- ============================================================================
-- Epic 6 — Billing & Payments
-- Migration 6: scheduled-job SQL functions + invoice-PDF background job
-- Ref: BACKEND_ARCHITECTURE.md §26, §27; BACKEND_EXECUTION_PLAN.md Epic 6 §12
--
-- Per §27: "Implementation: pg_cron... triggering either a Postgres function
-- directly (for pure-DB work) or a database webhook to an Edge Function".
-- All four jobs below are pure-DB work — plain SQL functions, SECURITY
-- DEFINER (each sweeps across every tenant, which is why cross-tenant
-- visibility is required — the same justification
-- platform.drain_notification_outbox/platform.notify_on_provisioning_event
-- (Epic 4) already established for cross-tenant sweep functions). None of
-- these functions registers an actual pg_cron schedule entry — matching the
-- established "staged structurally, not registered" precedent
-- (EPIC_3_COMPLETION_REPORT.md's GPS retention purge,
-- EPIC_4_COMPLETION_REPORT.md's notification-dispatch polling trigger):
-- pg_cron is not installed in this project (confirmed live in
-- EPIC_4_DEPLOYMENT_AUDIT.md §1) — registering a schedule against an
-- extension that isn't installed would fail outright, so every function
-- here is fully correct and callable on-demand (by an operator, a test, or
-- a future pg_cron webhook) with only the actual schedule entry out of
-- scope, consistent with every prior Epic's identical limitation.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- billing.generate_recurring_ledger_items — "Recurring billing ledger
-- generation" (§27). Set-based (EPIC_4_REVIEW.md H4 lesson: no per-row
-- loop for a tenant-wide, potentially large fan-out). Idempotent under
-- re-run via ON CONFLICT DO NOTHING against
-- billing_ledger_items_child_fee_period_key (migration 2) — the Acceptance
-- Criteria's own "no duplicates on job re-run" requirement.
--
-- v1 scope: cycle IN (monthly, once_per_year) only. cycle='per_term' is
-- deliberately not generated by this function — no term-calendar table
-- exists anywhere in Epic 1-5's schema to derive real term boundaries from
-- (academic.classrooms has no term/semester concept), and fabricating an
-- arbitrary fixed cadence (e.g. "every 4 months") would silently misbill
-- real tenants rather than correctly bill nothing until a real term
-- calendar exists. cycle='one_time' is never auto-generated by design (a
-- one-time fee is billed ad-hoc via generate_invoice or a direct manager
-- insert, migration 4's billing_ledger_items_insert_manager policy).
-- Documented explicitly in EPIC_6_COMPLETION_REPORT.md's Known Limitations,
-- not silently dropped.
-- ---------------------------------------------------------------------------
create or replace function billing.generate_recurring_ledger_items()
returns int
security definer
set search_path = ''
language plpgsql
as $$
declare
  v_inserted int;
begin
  with candidates as (
    select fi.id as fee_item_id, fi.tenant_id, fi.price, c.id as child_id,
           to_char(current_date, 'YYYY-MM') as period_label,
           (date_trunc('month', current_date) + interval '1 month' - interval '1 day')::date as due_date
    from billing.fee_items fi
    join academic.children c on c.tenant_id = fi.tenant_id and c.deleted_at is null
    where fi.active and fi.cycle = 'monthly' and fi.scope = 'all'

    union all

    select fi.id, fi.tenant_id, fi.price, fa.child_id,
           to_char(current_date, 'YYYY-MM'),
           (date_trunc('month', current_date) + interval '1 month' - interval '1 day')::date
    from billing.fee_items fi
    join billing.fee_item_applicability fa on fa.fee_item_id = fi.id
    join academic.children c on c.id = fa.child_id and c.deleted_at is null
    where fi.active and fi.cycle = 'monthly' and fi.scope = 'optional'

    union all

    select fi.id, fi.tenant_id, fi.price, c.id,
           to_char(current_date, 'YYYY'),
           (date_trunc('year', current_date) + interval '1 year' - interval '1 day')::date
    from billing.fee_items fi
    join academic.children c on c.tenant_id = fi.tenant_id and c.deleted_at is null
    where fi.active and fi.cycle = 'once_per_year' and fi.scope = 'all'

    union all

    select fi.id, fi.tenant_id, fi.price, fa.child_id,
           to_char(current_date, 'YYYY'),
           (date_trunc('year', current_date) + interval '1 year' - interval '1 day')::date
    from billing.fee_items fi
    join billing.fee_item_applicability fa on fa.fee_item_id = fi.id
    join academic.children c on c.id = fa.child_id and c.deleted_at is null
    where fi.active and fi.cycle = 'once_per_year' and fi.scope = 'optional'
  ),
  inserted as (
    insert into billing.billing_ledger_items (tenant_id, child_id, fee_item_id, period_label, amount_due, due_date, status)
    select tenant_id, child_id, fee_item_id, period_label, price, due_date,
           case when due_date <= current_date then 'due' else 'unbilled' end
    from candidates
    on conflict (child_id, fee_item_id, period_label) do nothing
    returning id
  )
  select count(*) into v_inserted from inserted;

  return v_inserted;
end;
$$;

comment on function billing.generate_recurring_ledger_items() is
  '"Recurring billing ledger generation" (§27). Set-based, cross-tenant. Idempotent under re-run (unique (child_id, fee_item_id, period_label), ON CONFLICT DO NOTHING). monthly + once_per_year only in v1 — see this file''s header for why per_term is out of scope.';

revoke all on function billing.generate_recurring_ledger_items from public;
grant execute on function billing.generate_recurring_ledger_items to service_role;

-- ---------------------------------------------------------------------------
-- billing.roll_up_billing_status — "Billing status roll-up" (§27). Set-based
-- UPDATEs across both stored-status tables (§3.38/§3.40's explicit
-- unification).
-- ---------------------------------------------------------------------------
create or replace function billing.roll_up_billing_status()
returns int
security definer
set search_path = ''
language plpgsql
as $$
declare
  v_total int := 0;
  v_n     int;
begin
  update billing.billing_ledger_items set status = 'overdue' where status in ('due', 'partially_paid') and due_date < current_date;
  get diagnostics v_n = row_count; v_total := v_total + v_n;

  update billing.billing_ledger_items set status = 'due' where status = 'unbilled' and due_date <= current_date;
  get diagnostics v_n = row_count; v_total := v_total + v_n;

  update billing.installment_schedule_entries set status = 'overdue' where status in ('due', 'partially_paid') and due_date < current_date;
  get diagnostics v_n = row_count; v_total := v_total + v_n;

  update billing.installment_schedule_entries set status = 'due' where status = 'unbilled' and due_date <= current_date;
  get diagnostics v_n = row_count; v_total := v_total + v_n;

  return v_total;
end;
$$;

comment on function billing.roll_up_billing_status() is
  '"Billing status roll-up" (§27). Set-based, cross-tenant. Recomputes billing.billing_ledger_items.status/billing.installment_schedule_entries.status from due_date — both stored, job-maintained columns (§3.38/§3.40), never computed at read time.';

revoke all on function billing.roll_up_billing_status from public;
grant execute on function billing.roll_up_billing_status to service_role;

-- ---------------------------------------------------------------------------
-- billing.send_payment_reminders — "Payment reminder cadence" (§27, §16:
-- T-3/T0/T+3 days from due_date). Set-based. No de-duplication table exists
-- for reminder-sends — this function assumes it is invoked at most once per
-- day (documented in EPIC_6_COMPLETION_REPORT.md's Known Limitations,
-- consistent with not inventing an undocumented schema table to solve a
-- problem the architecture doc doesn't name).
-- ---------------------------------------------------------------------------
create or replace function billing.send_payment_reminders()
returns int
security definer
set search_path = ''
language plpgsql
as $$
declare
  v_count int;
begin
  with reminded as (
    insert into comms.notifications (tenant_id, recipient_type, recipient_id, category, title, body, deep_link, severity)
    select distinct bli.tenant_id, 'guardian', cgl.guardian_id,
           'payment_due',
           case when bli.due_date < current_date then 'Payment overdue' when bli.due_date = current_date then 'Payment due today' else 'Payment due soon' end,
           fi.name || ' — ' || bli.amount_due::text,
           'app://payments/ledger/' || bli.id::text,
           case when bli.due_date < current_date then 'urgent' else 'info' end
    from billing.billing_ledger_items bli
    join billing.fee_items fi on fi.id = bli.fee_item_id
    join academic.child_guardian_links cgl on cgl.child_id = bli.child_id
    join identity.guardian_profiles g on g.id = cgl.guardian_id
    where bli.status in ('due', 'overdue', 'partially_paid')
      and g.deleted_at is null
      and (bli.due_date - current_date) in (3, 0, -3)
    returning 1
  )
  select count(*) into v_count from reminded;

  return v_count;
end;
$$;

comment on function billing.send_payment_reminders() is
  '"Payment reminder cadence" (§27, §16). Set-based, cross-tenant. Fires at T-3/T0/T+3 days relative to due_date. Assumes at-most-once-per-day invocation (no reminder-send-log table exists to de-duplicate an intra-day re-run).';

revoke all on function billing.send_payment_reminders from public;
grant execute on function billing.send_payment_reminders to service_role;

-- ---------------------------------------------------------------------------
-- billing.escalate_stale_pending_verifications — "Stale manual-payment
-- escalation" (§27, §20, §16: "Manual payment stuck in pending_verification
-- past SLA -> Manager"). Set-based. 48h SLA per §20's own named example.
-- ---------------------------------------------------------------------------
create or replace function billing.escalate_stale_pending_verifications()
returns int
security definer
set search_path = ''
language plpgsql
as $$
declare
  v_count int;
begin
  with escalated as (
    insert into comms.notifications (tenant_id, recipient_type, recipient_id, category, title, body, deep_link, severity)
    select distinct pt.tenant_id, 'staff', sp.id,
           'payment', 'Payment verification overdue',
           'A manual payment has been pending verification for over 48 hours.',
           'app://payments/' || pt.id::text, 'attention'
    from billing.payment_transactions pt
    join identity.staff_profiles sp on sp.tenant_id = pt.tenant_id and sp.role = 'manager' and sp.deleted_at is null
    where pt.status = 'pending_verification' and pt.initiated_at < now() - interval '48 hours'
    returning 1
  )
  select count(*) into v_count from escalated;

  return v_count;
end;
$$;

comment on function billing.escalate_stale_pending_verifications() is
  '"Stale manual-payment escalation" (§27, §20). Set-based, cross-tenant. 48h SLA. Notifies every manager in the affected tenant (not a per-row loop — a single set-based INSERT...SELECT).';

revoke all on function billing.escalate_stale_pending_verifications from public;
grant execute on function billing.escalate_stale_pending_verifications to service_role;

-- ---------------------------------------------------------------------------
-- Invoice PDF generation background job (§11, §26: "Invoice PDF generation
-- | generate_invoice RPC | Render PDF, upload to generated-documents
-- bucket, link invoices.pdf_object_id"). A trigger, not inline logic inside
-- generate_invoice, mirrors comms.notifications' dispatch-enqueue trigger
-- (Epic 4) exactly — fires regardless of write path, and keeps
-- generate_invoice's own transaction free of an external-service-adjacent
-- concern (matches §14.1's own RPC-vs-Edge-Function split: PDF rendering
-- belongs in an Edge Function, generate-invoice-pdf, migration 7's sibling
-- Edge Function file).
-- ---------------------------------------------------------------------------
create or replace function billing.enqueue_invoice_pdf_job()
returns trigger
language plpgsql
as $$
begin
  insert into jobs.background_job_queue (job_type, payload)
  values ('invoice_pdf_generation', jsonb_build_object('invoiceId', new.id));

  return new;
end;
$$;

create trigger trg_invoices_enqueue_pdf_job
  after insert on billing.invoices
  for each row execute function billing.enqueue_invoice_pdf_job();
